$ANSIBLE_VAULT;1.1;AES256
32366138656538643131663535396363613731613061323761336263643137363636633433383962
3737633238343462316336383566356131666265306261360a366434633635353130373030303837
33623531383038613130346237633162343335336432636261306361316161306132366566613338
3139363765663636300a353063616634646339643430323435616538623662616461363066646334
62363635666632643537333533393265353036626630666361363262643033613831616536633537
32306264346465623466333539353566666165326434653963343665333831643166323035663135
64306363363132663661623036363734373564636434616233336431613230663036316439373862
34373736316135653039343933333366303437316239306131313433623734303335336236383838
6533
