---
- hosts: webservers
  tasks:
    - name: Check web page
      uri:
        url: http://localhost
        status_code: 200

- hosts: appservers
  tasks:
    - name: Check API root
      uri:
        url: http://localhost:3000/
        status_code: 200
    - name: Check API /users
      uri:
        url: http://localhost:3000/users
        status_code: 200
